strict-sigcheck = false

[Twitter-Piko]
app-name = "Twitter"
brand = "Piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"

[Twitter-Piko.patches]
"github:crimera/piko" = ["Bring back twitter", "Browse tweet object", "Dynamic color"]
"gitlab:inotia00/piko-shim" = []

[X-Piko]
app-name = "X"
brand = "Piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"

[X-Piko.patches]
"github:crimera/piko" = ["Browse tweet object", "Dynamic color"]
"gitlab:inotia00/piko-shim" = []
