strict-sigcheck = false

[X-Twitter]
brand = "piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"

[X-Twitter.patches]
"github:crimera/piko" = ["Bring back twitter", "Browse tweet object", "Dynamic color"]
"gitlab:inotia00/piko-shim" = []
