strict-sigcheck = false

[Twitter-Piko]
enabled = true
app-name = "Twitter"
brand = "Piko"
# version = "12.2.0-release.0"
version = "12.2.1-release.0"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
# skip-sigcheck = true

[Twitter-Piko.patches]
"github:crimera/piko" = ["Bring back twitter", "Browse tweet object", "Dynamic color"] # Fetch Latest Stable Patch
# "github:crimera/piko" = { version = "dev", include = ["Bring back twitter", "Browse tweet object", "Dynamic color"] } # Fetch Latest Dev Patch
"gitlab:inotia00/x-shim" = []

[X-Piko]
enabled = true
app-name = "X"
brand = "Piko"
# version = "12.2.0-release.0"
version = "12.2.1-release.0"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
# skip-sigcheck = true

[X-Piko.patches]
"github:crimera/piko" = ["Browse tweet object", "Dynamic color"] # Fetch Latest Stable Patch
# "github:crimera/piko" = { version = "dev", include = ["Browse tweet object", "Dynamic color"] } # Fetch Latest Dev Patch
"gitlab:inotia00/x-shim" = []

[Instagram]
enabled = true
app-name = "Instagram"
brand = "Piko"
version = "auto"
# version = "430.0.0.53.80"
github-dlurl = "https://github.com/krvstek/uni-storage/releases/tag/instagram"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
arch = "arm64-v8a"

[Instagram.patches]
"github:crimera/piko" = [] #Fetch Latest Stable Patch
# "github:crimera/piko" = { version = "dev", include = [] } # Fetch Latest Dev Patch

[Facebook]
enabled = true
app-name = "Facebook"
brand = "De-Vanced"
version = "auto"
# version = "566.0.0.48.73"
github-dlurl = "https://github.com/nvbangg/builder-for-morphe/releases/tag/com.facebook.katana"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
uptodown-durl = "https://facebook.en.uptodown.com/android"
arch = "arm64-v8a"

[Facebook.patches]
"github:RookieEnough/De-Vanced" = []

[Messenger]
enabled = true
app-name = "Facebook Messenger"
brand = "De-Vanced"
version = "auto"
# version = "566.0.0.57.86"
github-dlurl = "https://github.com/nvbangg/builder-for-morphe/releases/tag/com.facebook.orca"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-technologies-llc/messenger/"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
arch = "arm64-v8a"

[Messenger.patches]
"github:RookieEnough/De-Vanced" = []

[Threads]
enabled = true
app-name = "Threads"
brand = "De-Vanced"
github-dlurl = "https://github.com/nvbangg/builder-for-morphe/releases/tag/com.instagram.barcelona"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/threads-an-instagram-app/"
uptodown-dlurl = "https://threads.en.uptodown.com/android"
arch = "arm64-v8a"

[Threads.patches]
"github:RookieEnough/De-Vanced" = []

[Hola-VPN]
enabled = true
app-name = "Hola-VPN"
brand = "Rushi"
uptodown-dlurl = "https://holavpn.en.uptodown.com/android"
arch = "arm64-v8a"
changelog-keywords = ["Hola VPN"]

[Hola-VPN.patches]
"github:rushiranpise/morphe-patches" = []

[TeraBox]
enabled = true
app-name = "TeraBox"
brand = "Rushi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/flextech-inc/terabox-cloud-storage-cloud-backup-data-backup/"
uptodown-dlurl = "https://terabox.en.uptodown.com/android"
changelog-keywords = ["TeraBox"]

[TeraBox.patches]
"github:rushiranpise/morphe-patches" = []

[Proton-VPN-Rushi]
enabled = true
app-name = "Proton-VPN"
brand = "Rushi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn/"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
changelog-keywords = ["Proton VPN"]

[Proton-VPN-Rushi.patches]
"github:rushiranpise/morphe-patches" = []

[Windscribe-VPN]
enabled = true
app-name = "Windscribe-VPN"
brand = "Rushi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/windscribe/windscribe-vpn/"
uptodown-dlurl = "https://windscribe.en.uptodown.com/android"
changelog-keywords = ["Windscribe"]

[Windscribe-VPN.patches]
"github:rushiranpise/morphe-patches" = []

[Proton-VPN-Paresh]
enabled = true
app-name = "Proton-VPN"
brand = "Paresh"
github-dlurl = "https://github.com/nvbangg/builder-for-morphe/releases/tag/ch.protonvpn.android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn/"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
skip-sigcheck = true
changelog-keywords = ["Proton VPN"]

[Proton-VPN-Paresh.patches]
# "gitlab:Paresh-Maheshwari/paresh-patches" = [] # Fetch Latest Stable Patch
"gitlab:Paresh-Maheshwari/paresh-patches" = { version = "dev", include = [] } # Fetch Latest Dev Patch
